- name: create disk ({{ instance_disk_size }} GB) for {{ game }}
  gcp_compute_disk:
    name: "disk-{{ game }}-{{ discord_voice_channel_id }}"
    size_gb: "{{ instance_disk_size }}"
    source_image: "projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts"
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: present
  register: disk

- name: create a network
  gcp_compute_network:
    name: "default"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: present
  register: network

- name: create a address for {{ game }}-{{ discord_voice_channel_id }}
  gcp_compute_address:
    name: "address-{{ game }}-{{ discord_voice_channel_id }}"
    region: "{{ gcp_region }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: present
  register: address

- name: create a instance "{{ game }}-{{ discord_voice_channel_id }}" size {{ machine_type }}
  gcp_compute_instance:
    state: present
    deletion_protection: false
    name: "{{ game }}-{{ discord_voice_channel_id }}"
    machine_type: "{{ machine_type }}"
    disks:
      - auto_delete: true
        boot: true
        source: "{{ disk }}"
    network_interfaces:
      - network: "{{ network }}"
        access_configs:
          - name: "External NAT"
            nat_ip: "{{ address }}"
            type: "ONE_TO_ONE_NAT"
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
  register: instance

- name: ensure firewall rule is created (ssh-server)
  gcp_compute_firewall:
    name: allow-ssh
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    allowed:
      - ip_protocol: tcp
        ports:
          - "22"
    target_tags:
      - ssh-server
    state: present

- name: ensure firewall rule is created ({{ game }}-server)
  gcp_compute_firewall:
    name: allow-{{ game }}
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    allowed: "{{ game_firewall_config }}"
    target_tags:
      - "{{ game }}-server"
    state: present

- name: Wait for SSH to come up {{ address.address }}
  wait_for:
    host: "{{ address.address }}"
    port: 22
    delay: 10
    timeout: 60

- name: Add host to groupname
  add_host:
    hostname: "{{ address.address }}"
    groupname: "{{ game }}_{{ discord_voice_channel_id }}_hosts"
